### ISSUE TITLE
Additional changes in R

### ISSUE THREAD

**Issue by kaanokay** [cran/BioCircos#2]
Hi,

First of all, I would like to thank you for this nice R package.

I would like to ask several question about additional changes in circos plot with using R.

1) How can I add to UCSC track (karyotype) to my figure?
2) It is possible to save figure with .pdf extension? How can I adjust my figure without .pdf extension?
3) Detailed explanation of this package is avaiable for Java, but do you think to add such detailed explanation for R computation envrionment?

Thanks for reply and interest.

Best regards.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and potentially URLs in the `DESCRIPTION` file. Thanks!
